### ISSUE TITLE
Use GitHub API to automatically fetch the contributions (issue reply, PRs, code reviews) for a community member

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-oa#3]

**Comment by Zxilly** [comment]
https://github.com/Zxilly/WeeklyReportGenerator
This can be a reference. 
But plz notice, GitHub change the API on activities. So the filter on activities now have bugs.

**Comment by hsluoyz** [comment]
@Zxilly this is awesome. So do you use this tool to generate our previous weekly reports?

**Comment by Zxilly** [comment]
@hsluoyz yes

**Comment by hsluoyz** [comment]
@MRGUOKING @1340908470 plz refer to Zxilly's work.

**Comment by MRGUOKING** [comment]
@Zxilly Thank you very much. I think it will be helpful to me

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casbin-oa/pull/6
