### ISSUE TITLE
Use proxy to access GitHub APIs

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-oa#43]
The GitHub API calls fails sometimes in some areas:

https://github.com/casbin/casbin-oa/blob/c9b57ba305f32c63bdc3ba7c640c3cd47235b5cb/util/webhookAPI.go#L41-L56

We need to use proxy to access these APIs.

**Comment by hsluoyz** [comment]
@Steve0x2a there's still a small problem here.

**Comment by Steve0x2a** [comment]
> @Steve0x2a there's still a small problem here.

I will push a commit to solve this problem today.
