### ISSUE TITLE
[frontend] fix the bug that the theme color doesn't work for yarn start

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casbin-oa#49]
We use craco (https://ant.design/docs/react/use-with-create-react-app#Customize-Theme) to customize the theme color for Antd, but in the current code, the new theme color only works for `yarn build`, it doesn't work for `yarn start`. This needs to be fixed.

**Comment by hsluoyz** [comment]
@Undertone0809

**Comment by imp2002** [comment]
Sorry, I can't reappear this bug.

Try customize the theme color either in `craco.config.js` or in a new `.less` file, it both works normally with `yarn start`.

![image](https://user-images.githubusercontent.com/41513919/187064785-8bb60c37-cda6-451b-92a5-0f378127558b.png)

![image](https://user-images.githubusercontent.com/41513919/187064790-75d02b9e-165c-4296-88d1-40fff59f1e94.png)

![image](https://user-images.githubusercontent.com/41513919/187064840-01bd4774-4523-4125-a2c1-f1730480e2d5.png)

**Comment by hsluoyz** [comment]
Indeed like this, no problem now
